name: Username Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install requests

      - name: Run Checker
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: python stat.py
